repos:
  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        files: \.py
        entry: duty format
      - id: lint
        name: lint
        language: system
        files: \.py
        entry: duty lint
      - id: typecheck
        name: typecheck
        language: system
        files: \.py
        entry: duty type-check
      - id: secure
        name: secure
        entry: duty secure
        language: system
        pass_filenames: false
      - id: docs
        name: docs
        entry: duty docs
        language: system
        pass_filenames: false
      - id: test
        name: test
        entry: duty test
        language: system
        pass_filenames: false

